name: Typecheck
on: push
jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: Install modules
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Run TypeScript
        run: yarn ts
